# -*- coding: utf-8 -*-
"""Enzo _TP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fhsl5CuDJAfBFAv-s4xH9jRtWZQozy38

# TRABAJO PRÁCTICO INTEGRADOR N°1

## Sistema de Análisis de Documentos Digitalizados

---

**Información del Estudiante:**
- **Nombre y Apellido:** [COMPLETAR]
- **Fecha de Entrega:** 24 de Septiembre de 2025
- **Materia:** Procesamiento de Imágenes - IFTS24

---

### Objetivo

Desarrollar un sistema básico de análisis automático de documentos digitalizados que integre las técnicas de procesamiento de imágenes estudiadas en el curso.

### Estructura del Trabajo

| Parte | Descripción | Peso |
|-------|-------------|------|
| **1** | Fundamentos Teóricos | 20% |
| **2** | Setup del Entorno | 15% |
| **3** | Análisis de Imágenes | 35% |
| **4** | Preprocessing Básico | 30% |

**Dataset requerido:** 3 imágenes de documentos con diferentes características (buena calidad, rotada, con problemas de iluminación)

---

# PARTE 1: Fundamentos Teóricos

## ¿Por qué Cuadernos Interactivos para IA y Ciencias de Datos?

### Diferencias Metodológicas Fundamentales

El trabajo en inteligencia artificial y ciencias de datos requiere un enfoque metodológico diferente al desarrollo de software tradicional. Mientras que la programación tradicional sigue un flujo lineal y predecible, el trabajo con datos es inherentemente iterativo y exploratorio.

**Programación Tradicional:**
```
Requisitos → Diseño → Implementación → Testing → Producto
```

**Investigación en IA/Datos:**
```
Hipótesis ⟷ Experimento ⟷ Análisis ⟷ Refinamiento ⟷ Nueva Hipótesis
```

### Ventajas de los Cuadernos Interactivos

1. **Narrativa Científica:** Permiten documentar el proceso de pensamiento, no solo el resultado final
2. **Iteración Rápida:** Ejecutar y modificar secciones específicas sin reejecutar todo el programa
3. **Visualización Inmediata:** Ver resultados inmediatamente después de cada paso
4. **Comunicación Efectiva:** Stakeholders no técnicos pueden seguir el proceso y entender decisiones
5. **Reproducibilidad:** Otros investigadores pueden replicar exactamente los experimentos

### Casos de Uso en la Industria

- **Google Research:** Publica papers con cuadernos que permiten reproducir experimentos
- **Netflix:** Usa cuadernos para análisis de datos de usuarios y recomendaciones
- **Uber:** Análisis de patrones de viajes y optimización de rutas
- **Kaggle:** Plataforma completa basada en cuadernos para competencias de machine learning

### Cuándo Usar Cada Herramienta

**Usar Cuadernos para:**
- Análisis exploratorio de datos
- Experimentación y prototipado
- Comunicación de resultados
- Educación y documentación

**Usar Scripts para:**
- Sistemas en producción
- Automatización de tareas repetitivas
- APIs y servicios web
- Pipelines de datos automatizados

En este trabajo práctico, usaremos cuadernos porque estamos en la fase de investigación y experimentación, donde necesitamos entender los datos, probar diferentes enfoques y documentar nuestros hallazgos.

---

# PARTE 2: Setup del Entorno

En esta sección vas a configurar tu entorno de trabajo de manera profesional. Un setup bien hecho te ahorra tiempo y errores durante todo el proyecto.

**Material de consulta:** `Utilidades_y_Plantillas.ipynb`

## 2.1 Importaciones Básicas

Importá las librerías necesarias para procesamiento de imágenes y visualización:
"""

# Commented out IPython magic to ensure Python compatibility.
# Importá aquí las librerías necesarias
# Necesitarás: numpy, matplotlib, opencv, y configuraciones básicas
#------------------------------------------------------------------#
import numpy as np                     # Para operaciones numéricas y matrices
import matplotlib.pyplot as plt        # Para mostrar imágenes y gráficos
import cv2                             # OpenCV: procesamiento de imágenes

#  Configuraciones básicas


# %matplotlib inline

# Cambiar estilo de gráficos (opcional)
plt.style.use('seaborn-v0_8')

"""## 2.2 Funciones Utilitarias

Implementá una función básica para cargar y mostrar información de imágenes:
"""

def cargar_imagen(ruta):
    """
    Carga una imagen desde una ruta y la convierte a RGB.
    Devuelve None si hay error.
    """
    imagen = cv2.imread(ruta)  # Leer imagen
    if imagen is None:
        print(f"⚠️ No se pudo cargar la imagen: {ruta}")
        return None

    imagen_rgb = cv2.cvtColor(imagen, cv2.COLOR_BGR2RGB)  # Convertir a RGB
    return imagen_rgb


def mostrar_info_imagen(imagen, titulo="Imagen"):
    """
    Muestra dimensiones, tipo, rango de valores y visualiza la imagen.
    """
    if imagen is None:
        print("⚠️ Imagen no válida")
        return

    print("📐 Dimensiones:", imagen.shape)
    print("🔢 Tipo:", imagen.dtype)
    print("🌈 Rango:", imagen.min(), "-", imagen.max())

    plt.imshow(imagen)
    plt.title(titulo)
    plt.axis('off')
    plt.show()


# 🧪 Uso del programa
# Cambia "imagen.jpg" por la ruta de tu archivo
ruta_imagen = "imagen.jpg"

# Cargar la imagen en una variable
imagen = cargar_imagen(ruta_imagen)

# Mostrar información y la imagen
mostrar_info_imagen(imagen, "Imagen cargada")

"""## 2.3 Verificación del Setup

Probá que todo funciona creando una imagen sintética simple:
"""

# Creá una imagen sintética simple (ej: gradiente o patrón)
# Probá tus funciones con esta imagen

"""---

# PARTE 3: Análisis de Tu Dataset

Ahora vas a trabajar con tu dataset de 3 documentos. Esta parte es clave para entender qué problemas tenés que resolver.

**Preparación del Dataset:**
- Creá una carpeta llamada `dataset/` en la misma ubicación que este notebook
- Incluí exactamente 3 imágenes de documentos:
  1. Una de buena calidad (bien iluminada, recta)
  2. Una rotada o inclinada
  3. Una con problemas (oscura, borrosa, o con sombras)

## 3.1 Carga de las Imágenes

**Material de consulta:** `002/TEO/LeerImagenColor.ipynb`
"""

# Define las rutas a tus 3 imágenes
rutas_imagenes = [
    "dataset/imagen1.jpg",  # Buena calidad
    "dataset/imagen2.jpg",  # Rotada
    "dataset/imagen3.jpg"   # Con problemas
]

# Carga las 3 imágenes usando tu función
imagenes = []
nombres = ["Buena Calidad", "Rotada", "Con Problemas"]

# ✅ Cargar cada imagen en la lista
for ruta in rutas_imagenes:
    img = cargar_imagen(ruta)
    imagenes.append(img)

# ✅ Mostrar información de cada imagen
for img, nombre in zip(imagenes, nombres):
    mostrar_info_imagen(img, nombre)

"""## 3.2 Inspección Visual y Análisis

**Material de consulta:** `002/Fundamentos_Imagen_Digital.ipynb`
"""

# Mostrar las 3 imágenes lado a lado con sus nombres
# Usa subplots de matplotlib

fig, axs = plt.subplots(1, 3, figsize=(15, 5))  # 1 fila, 3 columnas

for i, (img, nombre) in enumerate(zip(imagenes, nombres)):
    axs[i].imshow(img)
    axs[i].set_title(nombre)
    axs[i].axis('off')  # Oculta los ejes para mejor visualización

plt.tight_layout()
plt.show()

# Mostrar información básica y el histograma de cada imagen

for img, nombre in zip(imagenes, nombres):
    if img is None:
        print(f"⚠️ No se pudo procesar la imagen: {nombre}")
        continue

    # --- Información básica ---
    print(f"🔎 Análisis de: {nombre}")
    mostrar_info_imagen(img, nombre)  # Usa la función que hicimos antes

    # --- Histograma ---
    # Si la imagen es a color, la convertimos a escala de grises para el histograma
    if len(img.shape) == 3:
        img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    else:
        img_gray = img

    plt.figure(figsize=(6, 4))
    plt.hist(img_gray.ravel(), bins=256, color='gray', alpha=0.8)
    plt.title(f"Histograma - {nombre}")
    plt.xlabel("Valor de intensidad")
    plt.ylabel("Frecuencia")
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.show()

"""## 3.3 Identificación de Problemas

Basándote en tu inspección visual, identificá los problemas principales de cada imagen:

**Imagen 1 (Buena Calidad):**
- Problemas identificados: [COMPLETAR]
- Preprocessing necesario: [COMPLETAR]

**Imagen 2 (Rotada):**
- Problemas identificados: [COMPLETAR]
- Preprocessing necesario: [COMPLETAR]

**Imagen 3 (Con Problemas):**
- Problemas identificados: [COMPLETAR]
- Preprocessing necesario: [COMPLETAR]

---

# PARTE 4: Preprocessing Básico

Ahora vas a aplicar técnicas de preprocessing para mejorar cada imagen. Trabajá con una imagen por vez.

## 4.1 Segmentación Básica

Separar el documento del fondo es el primer paso crítico.

**Material de consulta:** `Segmentacion.ipynb` (especialmente las funciones de umbralización)
"""

# Elegí UNA de tus imágenes para trabajar primero
imagen_trabajo = imagenes[0]  # Cambiá el índice (0, 1 o 2) según la imagen que quieras

# ✅ Convertir a escala de grises
imagen_gris = cv2.cvtColor(imagen_trabajo, cv2.COLOR_RGB2GRAY)

# Mostrar resultado
plt.imshow(imagen_gris, cmap='gray')
plt.title("Imagen en escala de grises")
plt.axis('off')
plt.show()

# Aplicar segmentación por umbralización
# Probe distintos valores de 'umbral' (entre 0 y 255) para ver cuál separa mejor los objetos del fondo
umbrales = [50, 100, 150, 180, 200]

plt.figure(figsize=(15, 5))

for i, u in enumerate(umbrales):
    _, img_umbral = cv2.threshold(imagen_gris, u, 255, cv2.THRESH_BINARY)
    plt.subplot(1, 5, i + 1)
    plt.imshow(img_umbral, cmap='gray')
    plt.title(f"Umbral = {u}")
    plt.axis('off')

plt.tight_layout()
plt.show()

# Supongamos que ya tenemos:
# imagen_trabajo -> imagen original
# imagen_gris -> versión en escala de grises
# imagen_umbral -> máscara binaria (resultado del umbral elegido)

plt.figure(figsize=(15, 5))

# Imagen original
plt.subplot(1, 3, 1)
plt.imshow(imagen_trabajo)
plt.title("Original")
plt.axis('off')

# Escala de grises
plt.subplot(1, 3, 2)
plt.imshow(imagen_gris, cmap='gray')
plt.title("Escala de grises")
plt.axis('off')

# Máscara binaria
plt.subplot(1, 3, 3)
plt.imshow(imagen_umbral, cmap='gray')
plt.title("Máscara umbral")
plt.axis('off')

plt.tight_layout()
plt.show()

"""## 4.2 Mejora de Calidad

**Material de consulta:** `Mejora_Imagen_Ecualizacion.ipynb`
"""

# ✅ Aplicar ecualización de histograma si hay problemas de contraste
# Solo se aplica sobre la imagen en escala de grises
imagen_ecualizada = cv2.equalizeHist(imagen_gris)

# Mostrar comparación: original vs ecualizada
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(imagen_gris, cmap='gray')
plt.title("Original (gris)")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(imagen_ecualizada, cmap='gray')
plt.title("Ecualizada")
plt.axis('off')

plt.tight_layout()
plt.show()

# Supongamos que imagen_trabajo es la imagen que está rotada
# Angulo de rotación (en grados). Ajustá según necesites
angulo = -90  # negativo = rotación en sentido horario

# Obtener dimensiones de la imagen
(h, w) = imagen_trabajo.shape[:2]
centro = (w // 2, h // 2)

# Matriz de rotación
M = cv2.getRotationMatrix2D(centro, angulo, 1.0)  # escala=1.0

# Aplicar transformación afín (rotación)
imagen_corregida = cv2.warpAffine(imagen_trabajo, M, (w, h))

# Mostrar comparación
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(imagen_trabajo)
plt.title("Original (rotada)")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(imagen_corregida)
plt.title("Corregida")
plt.axis('off')

plt.tight_layout()
plt.show()

"""## 4.3 Comparación de Resultados"""

# Supongamos que:
# imagen_trabajo -> imagen original
# imagen_procesada -> imagen después de rotación, ecualización o umbralización

plt.figure(figsize=(10, 5))

# Imagen original
plt.subplot(1, 2, 1)
plt.imshow(imagen_trabajo)
plt.title("Original")
plt.axis('off')

# Imagen procesada
plt.subplot(1, 2, 2)
plt.imshow(imagen_procesada, cmap='gray')  # si es binaria o gris
plt.title("Procesada")
plt.axis('off')

plt.tight_layout()
plt.show()

"""## 4.4 Aplicación a las Otras Imágenes

Repetí el proceso para tus otras 2 imágenes, adaptando las técnicas según los problemas específicos de cada una:
"""

# Función para procesar cada imagen
def procesar_imagen(img, nombre, umbral=120, angulo_rotacion=0, aplicar_ecualizacion=False):
    """
    Procesa una imagen según sus problemas específicos.

    Parámetros:
    - img: imagen original
    - nombre: título para visualización
    - umbral: valor para umbralización
    - angulo_rotacion: grados para corregir rotación
    - aplicar_ecualizacion: True si se necesita mejorar contraste
    """
    # 1️⃣ Corregir rotación si hace falta
    if angulo_rotacion != 0:
        (h, w) = img.shape[:2]
        centro = (w // 2, h // 2)
        M = cv2.getRotationMatrix2D(centro, angulo_rotacion, 1.0)
        img = cv2.warpAffine(img, M, (w, h))

    # 2️⃣ Convertir a escala de grises
    img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    # 3️⃣ Ecualizar si hace falta
    if aplicar_ecualizacion:
        img_gray = cv2.equalizeHist(img_gray)

    # 4️⃣ Umbralización
    _, img_umbral = cv2.threshold(img_gray, umbral, 255, cv2.THRESH_BINARY)

    # 5️⃣ Mostrar resultados lado a lado
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 3, 1)
    plt.imshow(img)
    plt.title(f"{nombre} - Original")
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(img_gray, cmap='gray')
    plt.title(f"{nombre} - Gris/Ecualizada")
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(img_umbral, cmap='gray')
    plt.title(f"{nombre} - Umbral")
    plt.axis('off')

    plt.tight_layout()
    plt.show()

    return img_gray, img_umbral

# 🔹 Procesar las otras dos imágenes
# Ajustá los parámetros según cada caso (rotación, contraste, umbral)
procesar_imagen(imagenes[1], nombres[1], umbral=130, angulo_rotacion=-90, aplicar_ecualizacion=False)
procesar_imagen(imagenes[2], nombres[2], umbral=100, angulo_rotacion=0, aplicar_ecualizacion=True)

# Seleccionar la tercera imagen
imagen_trabajo = imagenes[2]
nombre = nombres[2]

# 1️⃣ Convertir a escala de grises
imagen_gris = cv2.cvtColor(imagen_trabajo, cv2.COLOR_RGB2GRAY)

# 2️⃣ Ecualizar para mejorar contraste
imagen_ecualizada = cv2.equalizeHist(imagen_gris)

# 3️⃣ Aplicar umbralización
umbral = 100  # ajusta según necesites
_, imagen_umbral = cv2.threshold(imagen_ecualizada, umbral, 255, cv2.THRESH_BINARY)

# 4️⃣ Mostrar resultados: original, gris/ecualizada, máscara
plt.figure(figsize=(12, 5))

plt.subplot(1, 3, 1)
plt.imshow(imagen_trabajo)
plt.title(f"{nombre} - Original")
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(imagen_ecualizada, cmap='gray')
plt.title(f"{nombre} - Gris/Ecualizada")
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(imagen_umbral, cmap='gray')
plt.title(f"{nombre} - Umbral")
plt.axis('off')

plt.tight_layout()
plt.show()

"""## 4.5 Resultados Finales"""

# Supongamos que tenemos:
# imagenes -> lista de imágenes originales
# nombres -> nombres de cada imagen
# imagenes_procesadas -> lista de imágenes procesadas (grises/umbralizadas)

# Crear lista de imágenes procesadas para este ejemplo
imagenes_procesadas = []

# Procesar cada imagen según su caso (rotación, ecualización, umbralización)
# Ajusta parámetros según cada imagen
for i, img in enumerate(imagenes):
    # Parámetros de ejemplo, ajustables según cada imagen
    if i == 0:  # Buena calidad
        angulo = 0
        ecualizar = False
        umbral = 120
    elif i == 1:  # Rotada
        angulo = -90
        ecualizar = False
        umbral = 130
    else:       # Problemas de contraste
        angulo = 0
        ecualizar = True
        umbral = 100

    # Corregir rotación si aplica
    if angulo != 0:
        (h, w) = img.shape[:2]
        centro = (w // 2, h // 2)
        M = cv2.getRotationMatrix2D(centro, angulo, 1.0)
        img = cv2.warpAffine(img, M, (w, h))

    # Escala de grises
    img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    # Ecualizar si aplica
    if ecualizar:
        img_gray = cv2.equalizeHist(img_gray)

    # Umbralización
    _, img_umbral = cv2.threshold(img_gray, umbral, 255, cv2.THRESH_BINARY)

    # Guardar la versión procesada
    imagenes_procesadas.append(img_umbral)

# 📊 Mostrar grid: 2 filas x 3 columnas
plt.figure(figsize=(15, 8))

for i in range(3):
    # Imagen original
    plt.subplot(2, 3, i + 1)
    plt.imshow(imagenes[i])
    plt.title(f"Original - {nombres[i]}")
    plt.axis('off')

    # Imagen procesada
    plt.subplot(2, 3, i + 4)
    plt.imshow(imagenes_procesadas[i], cmap='gray')
    plt.title(f"Procesada - {nombres[i]}")
    plt.axis('off')

plt.tight_layout()
plt.show()

"""---

# REFLEXIÓN FINAL

## Análisis de Resultados

**¿Qué técnica fue más efectiva para cada tipo de problema?**

[COMPLETAR: Reflexioná sobre qué funcionó mejor para cada imagen]

**¿Qué desafíos encontraste durante el procesamiento?**

[COMPLETAR: Mencioná las dificultades técnicas que tuviste]

**¿En qué casos los resultados no fueron óptimos y por qué?**

[COMPLETAR: Sé crítico con tus resultados]

## Aprendizaje Adquirido

**¿Qué conceptos del curso fueron más útiles?**

[COMPLETAR: Conectá con el material visto en clase]

**¿Cómo podrías mejorar este sistema en futuras versiones?**

[COMPLETAR: Pensá en extensiones posibles]

---

## Entregables

1. Este notebook completamente ejecutado con resultados
2. Carpeta `dataset/` con tus 3 imágenes
3. Las reflexiones completadas

**Fecha de entrega:** 24 de Septiembre, 23:59

---
"""